### ISSUE TITLE
Talent points

### ISSUE THREAD

**Issue by maffboss** [Sorrow446/HLSE-Hogwarts-Legacy-Save-Editor#11]
@Sorrow446 I tried too add them with the last commits I saw in Github, but it did not seem too work. Is it already working too add talent points or am I too fast trying it out?

**Comment by Sorrow446** [comment]
It should be working, yep. Was there no error?

**Comment by maffboss** [comment]
What is the argument for it then @Sorrow446 ?
--talentpoints
--talent-points

![image](https://user-images.githubusercontent.com/109850729/218326613-9ddd81a7-7e0e-4225-be8e-e6be4c584f16.png)

**Comment by StealUrKill** [comment]
> What is the argument for it then @Sorrow446 ? --talentpoints --talent-points
> 
> ![image](https://user-images.githubusercontent.com/109850729/218326613-9ddd81a7-7e0e-4225-be8e-e6be4c584f16.png)

He has not updated the binaries so it should not be working

**Comment by maffboss** [comment]
If I download the files and just update it manually it doesnt work? Hmmm okay... Then I will wait!

**Comment by StealUrKill** [comment]
> If I download the files and just update it manually it doesnt work? Hmmm okay... Then I will wait!

I tried compiling them but i am not familiar with go.  I get these errors

`# command-line-arguments
.\main.go:66:31: undefined: ItemPairs
.\main.go:75:40: undefined: ItemPairs
.\main.go:81:16: undefined: ItemPairs
.\main.go:89:12: undefined: ItemPairs
.\main.go:104:20: undefined: Args
.\main.go:105:11: undefined: Args
`

**Comment by Sorrow446** [comment]
> > If I download the files and just update it manually it doesnt work? Hmmm okay... Then I will wait!
> 
> I tried compiling them but i am not familiar with go. I get these errors
> 
> command-line-arguments .\main.go:66:31: undefined: ItemPairs .\main.go:75:40: undefined: ItemPairs .\main.go:81:16: undefined: ItemPairs .\main.go:89:12: undefined: ItemPairs .\main.go:104:20: undefined: Args .\main.go:105:11: undefined: Args

go run main.go structs.go

**Comment by maffboss** [comment]
Is there a way I can do it as well? I download it again and replace the files in the folder. But that is not enough? @Sorrow446 

![image](https://user-images.githubusercontent.com/109850729/218328679-a00415e1-9195-410a-a2bc-eee7a6cad0b4.png)

**Comment by Sorrow446** [comment]
> If I download the files and just update it manually it doesnt work? Hmmm okay... Then I will wait!

I only update the binaries after a few changes otherwise people would get tired of constantly updating.
https://gofile.io/d/kcdbCS

**Comment by StealUrKill** [comment]
> > If I download the files and just update it manually it doesnt work? Hmmm okay... Then I will wait!
> 
> I only update the binaries after a few changes otherwise people would get tired of constantly updating. https://gofile.io/d/kcdbCS

yes sir, i actually got it to build. appreciate the feedback

**Comment by StealUrKill** [comment]
> Is there a way I can do it as well? I download it again and replace the files in the folder. But that is not enough? @Sorrow446
> 
> ![image](https://user-images.githubusercontent.com/109850729/218328679-a00415e1-9195-410a-a2bc-eee7a6cad0b4.png)

i  can message you the details. dont want to take up this space.

**Comment by StealUrKill** [comment]
> Is there a way I can do it as well? I download it again and replace the files in the folder. But that is not enough? @Sorrow446
> 

Download Git installer from https://git-scm.com/download/win and install it.
Download Go installer from https://go.dev/ and install it.



Create a directory and open a prompt within that directory and 
`git clone --recursive https://github.com/Sorrow446/HLSE-Hogwarts-Legacy-Save-Editor.git`
`cd HLSE-Hogwarts-Legacy-Save-Editor`
`go build`


this will make a main.exe and this is the binary to use the same way.

**Comment by StealUrKill** [comment]
> > Is there a way I can do it as well? I download it again and replace the files in the folder. But that is not enough? @Sorrow446
> 
> Download Git installer from https://git-scm.com/download/win and install it. Download Go installer from https://go.dev/ and install it.
> 
> Create a directory and open a prompt within that directory and `git clone --recursive https://github.com/Sorrow446/HLSE-Hogwarts-Legacy-Save-Editor.git` `cd HLSE-Hogwarts-Legacy-Save-Editor` `go build`
> 
> this will make a main.exe and this is the binary to use the same way.

but you might get an error lol...


panic: Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub

**Comment by Sorrow446** [comment]
> 

That's an issue with the 32-bit binary. CGO should be enabled by default.

**Comment by maffboss** [comment]
@Sorrow446 When do you think you make a release for this one? I already see a update in the read me hehe!

**Comment by StealUrKill** [comment]
> @Sorrow446 When do you think you make a release for this one? I already see a update in the read me hehe!

he pasted the link to one. it is confirmed working by me lol

**Comment by maffboss** [comment]
Works! Thanks!
