### ISSUE TITLE
--wand-flex Not Seem to Behave as Expected

### ISSUE THREAD

**Issue by zephyralistair** [Sorrow446/HLSE-Hogwarts-Legacy-Save-Editor#20]
Whatever my argument is, the wand flex is always set to Slightly springy.

**Comment by Sorrow446** [comment]
Fixed, sorry. https://github.com/Sorrow446/HLSE-Hogwarts-Legacy-Save-Editor/commit/0476538982cfc4af382c651edd94041666d52e52

Binary: https://gofile.io/d/u2vEll

**Comment by zephyralistair** [comment]
Thanks, mate! It's a great tool and has been very helpful.
