### ISSUE TITLE
Character select screen still shows old house icon

### ISSUE THREAD

**Issue by altermere** [Sorrow446/HLSE-Hogwarts-Legacy-Save-Editor#23]
I was able to change my house from Slytherin to Ravenclaw but the character select screen still shows Slytherin in the top left icon and my character is dressed in Slytherin colors. It's purely cosmetic but it bugs me a little.
Edit: I did read the workaround from the [other issue](https://github.com/Sorrow446/HLSE-Hogwarts-Legacy-Save-Editor/issues/1) but kinda lazy to replay the intro all the way to the sorting hat, also I managed to create my character without a last name before the patch and now the game is not letting me do that.

**Comment by Sorrow446** [comment]
Yep, fetches that from SaveGameList.sav. House robes should change fine in-game. Don't think it's worth the effort as the game should just rebuild it if you save your game, then reload it.
https://github.com/Sorrow446/HLAT-Hogwarts-Legacy-Appearance-Tool/issues/1

**Comment by altermere** [comment]
I found out I delete SaveGameList it gets recreated with info from the savegame, just replacing text in that file did nothing, it still overwrote my house with the old one. Replaced all occurrences of Slytherin with Ravenclaw in a manual save file (deleted all the others before that) in HxD and it fixed it. Did all that while game was running.
