### ISSUE TITLE
Items that cannot be added

### ISSUE THREAD

**Issue by QQ549387002** [Sorrow446/HLSE-Hogwarts-Legacy-Save-Editor#6]
咬人甘蓝 ：ChineseChompingCabbage 

曼德拉草： Mandrake

毒触手：  VenomousTentacula

1两耳草细枝: KnotgrassSprig

2嗅嗅皮毛:NifflerFur

3夜骐毛:ThestralHair

5巨怪鼻涕:TrollBogeys

6恶婆鸟羽毛:FwooperFeather

7恶犬毛皮:MongelFur

8月痴兽毛皮:MooncalfFur

10泥怪舌头:DugbogTongue

11流液草茎:FluxweedStem

13独角兽毛:UnicornHair

14猫狸子毛:KneazleFur

15球遁鸟羽毛:DiricawlFeather

16白鲜叶:DittanyLeaves

17紫角兽角:GraphornHorn

18绝音鸟羽毛:JobberknollFeather

19缩皱无花果果实:ShrivelfigFruit

21浦绒绒毛发:PuffskeinFur

23蜘蛛尖牙:SpiderFang

24蟾蜍疣:ToadWarts

25跳跳伞菌帽:LeapingToadstoolCaps

27香锦葵叶:MallowsweetLeaces

28鹰马翼羽毛:HippogriffFeather

**Comment by Sorrow446** [comment]
Adding items is planned. You can only edit quantities at the moment.

**Comment by QQ549387002** [comment]
I want to say that the above materials cannot be edited. My English is poor. I'm sorry
![1111](https://user-images.git
![1111](https://user-images.githubusercontent.com/125160163/218294171-5c995d34-3324-46bb-a6f4-7f30c938c92b.png)
hubusercontent.com/125160163/218294165-9e0b2a13-dcc3-4487-88f7-0dfee7fc88af.png)
